// Auto-generated by LibreLane
module top_chip(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input i_clk,
  input i_rst_n,
  input i_serial_rx,
  output o_serial_tx,
  input i_spi_ss_n,
  input i_spi_sclk,
  input i_spi_mosi,
  output o_spi_miso
);
endmodule
